name: Laravel Dusk Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dusk-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql, bcmath
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Configure environment
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan migrate --force

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 google-chrome-stable
        shell: bash

      - name: Set Chrome driver to run headless
        run: php artisan dusk:chrome-driver --detect

      - name: Run Dusk tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: password
          APP_URL: http://127.0.0.1
          CI: true # Disable test retries
        run: php artisan dusk --env=testing
